version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 202583917032.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build backend Docker image...
      - docker build -t backend ./backend
      - docker tag backend:latest 202583917032.dkr.ecr.ap-south-1.amazonaws.com/backend:latest

  post_build:
    commands:
      - echo Pushing backend image...
      - docker push 202583917032.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
      - echo Writing backend image definition...
      - printf '[{"name":"backend","imageUri":"202583917032.dkr.ecr.ap-south-1.amazonaws.com/backend:latest"}]' > b-imagedefinitions.json

artifacts:
  files:
    - b-imagedefinitions.json
